# Generated by Django 3.1.6 on 2021-02-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_ad_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
    ]
