# Generated by Django 3.1.6 on 2021-02-05 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_auto_20210203_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='DayStatusTable',
            fields=[
                ('statustable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.statustable')),
            ],
            bases=('advertiser_management.statustable',),
        ),
        migrations.CreateModel(
            name='HourStatusTable',
            fields=[
                ('statustable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.statustable')),
            ],
            bases=('advertiser_management.statustable',),
        ),
    ]
