# Generated by Django 3.1.6 on 2021-02-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_daystatustable_hourstatustable_statustable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustable',
            old_name='time',
            new_name='date',
        ),
    ]
